std = "vim"

[rules]
almost_swapped = "deny"
constant_table_comparison = "deny"
deprecated = "warn"
divide_by_zero = "deny"
duplicate_keys = "deny"
empty_if = "deny"
empty_loop = "deny"
global_usage = "allow"
high_cyclomatic_complexity = "warn"
if_same_then_else = "deny"
ifs_same_cond = "deny"
incorrect_standard_library_use = "deny"
manual_table_clone = "deny"
mismatched_arg_count = "deny"
mixed_table = "deny"
multiple_statements = "allow"
must_use = "deny"
parenthese_conditions = "deny"
shadowing = "warn"
unused_variable = "warn"
undefined_variable = "warn"

